### PR TITLE
Nancy

### PR DESCRIPTION
**Pull request by nancy-lin**
Hey guys, please let me know your comments and whether you can see my link and graphic. Thank you!! @dhorton06 @akorkm @liciasf @BEV13 @Menna16

### CODE REVIEW

**Comment by liciasf** [comment]
I agree with @Menna16 , you should include an image! Maybe an example of how apps look like using the different options / tool you mention?

**Comment by liciasf** [comment]
Great! I think it's ready to be merged! :+1:

**Comment by dhorton06** [comment]
Looks Good! :+1:

**Comment by BEV13** [comment]
:+1:

**Pull request merged**
