### PR TITLE
Network structure

### PR DESCRIPTION
**Pull request by dhorton06**
@nancy-lin @liciasf @akorkm @BEV13 @Menna16 

Here's my commit, please leave your feedback. Let me know if you have any questions/suggestions about what I did.

### CODE REVIEW

**Comment by akorkm** [comment]
@dhorton06 great post, love it! Do you think you could add a couple of lines to describe what's happening in the pic?

**Comment by dhorton06** [comment]
I've added a short description of the photo. Please let me know if you approve of my changes and will allow my commit to be merged.

Thanks,
Dave

**Comment by akorkm** [comment]
:+1:

**Comment by liciasf** [comment]
The description you added really helps! This might be a minor thing, but I just noticed we can add some formatting to our text, in case you also want to do it:

Use # to make the text in a line bigger (as a header) - e.g. #Trade-offs of hiring local vs. global
Use *\* to make text bold - e.g. **x, y, z are key factors**

**Comment by dhorton06** [comment]
The photo description has been changed to italics

**Comment by BEV13** [comment]
Let's merge this, I think it looks good. :+1:

**Comment by liciasf** [comment]
I agree with @BEV13 , good to go! :+1:

**Pull request merged**
