### PR TITLE
Create local-vs-regional-vs-global-hiring.md

### PR DESCRIPTION
**Pull request by liciasf**
@akorkm, @dhorton06 , @nancy-lin , @BEV13 , @Menna16: This is the first version of my document, describing the trade-offs that should be considered when deciding the location of a software development team. Could you please review it and let me know if you have any comments on how to improve it? :smile:

### CODE REVIEW

**Comment by BEV13** [comment]
Let's merge this. :+1:

**Comment by liciasf** [comment]
Thanks for the comments everyone, and for the :+1: @BEV13 . 

I have just updated my file to include some additional benefits of regional and global hiring that I had missed, as well as a link to an article that talks about some of the hidden benefits of global software development. 

Let me know if you're ok with the changes and I'll merge the PR. :smile:

**Comment by dhorton06** [comment]
:+1:

**Comment by BEV13** [comment]
:+1:

**Pull request merged**
