### PR TITLE
What platforms ap is saa s to use when you start a startup

### PR DESCRIPTION
**Pull request by dmitrykholodov**
@liciasf @BEV13  @akorkm @dhorton06 @nancy-lin  What do you think? Please give your feedback

### CODE REVIEW

**Comment by akorkm** [comment]
Good summary!
:+1:

**Comment by liciasf** [comment]
Hey @dmitrykholodov can you merge your file to the main branch? :+1:

**Comment by BEV13** [comment]
:+1:

**Comment by dhorton06** [comment]
Looks great, ready to merge! :+1:

**Comment by dmitrykholodov** [comment]
@liciasf  sure :+1:

**Pull request merged**
