### PR TITLE
Engineers ft vs shop vs contractor

### PR DESCRIPTION
**Pull request by akorkm**
@dhorton06 @nancy-lin @BEV13 @Menna16 @liciasf 
This is my first take on this, please let me know if you have any comments
p.s. Licia thank you for your previous comments!

### CODE REVIEW

**Comment by Menna16** [comment]
Good job!!!
Menna

**Comment by akorkm** [comment]
Thanks @Menna16 @BEV13 @dhorton06 @liciasf !
Would you please give me a go ahead if everything is ok?

**Comment by dhorton06** [comment]
Good to go! 👍🏻

David Horton

**Comment by BEV13** [comment]
Good to go for me. :+1:

**Comment by liciasf** [comment]
Agreed! Good to go! :+1:

**Pull request merged**
