### PR TITLE
Create how-to-leverage-experts-for-software-creation

### PR DESCRIPTION
**Pull request by BEV13**
Dear all, please give feedback! @akorkm @dhorton06 @Menna16 @nancy-lin @liciasf

### CODE REVIEW

**Comment by BEV13** [comment]
Guys, anymore comments for me? I made a few minor changes to my text. Can you give me a :+1: up for merging? @dhorton06 @Menna16 @akorkm @nancy-lin @liciasf

**Comment by liciasf** [comment]
@BEV13 I really liked how to explained how you'll apply what you learned to your specific professional context. 
Do you think you could expand on the key questions to ask programmers during an interview? I feel like that is one of the key takeaways from the course, and fits right into what you talk about in your file.

**Comment by dhorton06** [comment]
looks good, I'm good with you merging when your ready. :+1:

**Comment by dmitrykholodov** [comment]
I really liked your writeup and I think you will be able to practically applied what you learnt. I also like the pic :)

**Pull request merged**
